defaults:
  - _self_
  - data: mwz2.4 
  - model: trade 
  - callbacks: default
  - logger: tensorboard 
  - trainer: gpu
  - paths: default
  - extras: default
  - hydra: default
  - experiment: null
  - hparams_search: null
  - optional local: default
  - debug: null

task_name: "train"
tags: ["dev"]
precision: "high"
optimized_metric: val/jga
train: True
val: True
test: True
ckpt_path: null
seed: null


